use libc::{c_ulonglong, user_regs_struct};

#[derive(PartialEq, Debug, Clone, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum Syscall {
    Read,
    Write,
    Open,
    Close,
    Stat,
    Fstat,
    Lstat,
    Poll,
    Lseek,
    Mmap,
    Mprotect,
    Munmap,
    Brk,
    Rt_sigaction,
    Rt_sigprocmask,
    Rt_sigreturn,
    Ioctl,
    Pread64,
    Pwrite64,
    Readv,
    Writev,
    Access,
    Pipe,
    Select,
    Sched_yield,
    Mremap,
    Msync,
    Mincore,
    Madvise,
    Shmget,
    Shmat,
    Shmctl,
    Dup,
    Dup2,
    Pause,
    Nanosleep,
    Getitimer,
    Alarm,
    Setitimer,
    Getpid,
    Sendfile,
    Socket,
    Connect,
    Accept,
    Sendto,
    Recvfrom,
    Sendmsg,
    Recvmsg,
    Shutdown,
    Bind,
    Listen,
    Getsockname,
    Getpeername,
    Socketpair,
    Setsockopt,
    Getsockopt,
    Clone,
    Fork,
    Vfork,
    Execve,
    Exit,
    Wait4,
    Kill,
    Uname,
    Semget,
    Semop,
    Semctl,
    Shmdt,
    Msgget,
    Msgsnd,
    Msgrcv,
    Msgctl,
    Fcntl,
    Flock,
    Fsync,
    Fdatasync,
    Truncate,
    Ftruncate,
    Getdents,
    Getcwd,
    Chdir,
    Fchdir,
    Rename,
    Mkdir,
    Rmdir,
    Creat,
    Link,
    Unlink,
    Symlink,
    Readlink,
    Chmod,
    Fchmod,
    Chown,
    Fchown,
    Lchown,
    Umask,
    Gettimeofday,
    Getrlimit,
    Getrusage,
    Sysinfo,
    Times,
    Ptrace,
    Getuid,
    Syslog,
    Getgid,
    Setuid,
    Setgid,
    Geteuid,
    Getegid,
    Setpgid,
    Getppid,
    Getpgrp,
    Setsid,
    Setreuid,
    Setregid,
    Getgroups,
    Setgroups,
    Setresuid,
    Getresuid,
    Setresgid,
    Getresgid,
    Getpgid,
    Setfsuid,
    Setfsgid,
    Getsid,
    Capget,
    Capset,
    Rt_sigpending,
    Rt_sigtimedwait,
    Rt_sigqueueinfo,
    Rt_sigsuspend,
    Sigaltstack,
    Utime,
    Mknod,
    Uselib,
    Personality,
    Ustat,
    Statfs,
    Fstatfs,
    Sysfs,
    Getpriority,
    Setpriority,
    Sched_setparam,
    Sched_getparam,
    Sched_setscheduler,
    Sched_getscheduler,
    Sched_get_priority_max,
    Sched_get_priority_min,
    Sched_rr_get_interval,
    Mlock,
    Munlock,
    Mlockall,
    Munlockall,
    Vhangup,
    Modify_ldt,
    Pivot_root,
    _sysctl,
    Prctl,
    Arch_prctl,
    Adjtimex,
    Setrlimit,
    Chroot,
    Sync,
    Acct,
    Settimeofday,
    Mount,
    Umount2,
    Swapon,
    Swapoff,
    Reboot,
    Sethostname,
    Setdomainname,
    Iopl,
    Ioperm,
    Create_module,
    Init_module,
    Delete_module,
    Get_kernel_syms,
    Query_module,
    Quotactl,
    Nfsservctl,
    Getpmsg,
    Putpmsg,
    Afs_syscall,
    Tuxcall,
    Security,
    Gettid,
    Readahead,
    Setxattr,
    Lsetxattr,
    Fsetxattr,
    Getxattr,
    Lgetxattr,
    Fgetxattr,
    Listxattr,
    Llistxattr,
    Flistxattr,
    Removexattr,
    Lremovexattr,
    Fremovexattr,
    Tkill,
    Time,
    Futex,
    Sched_setaffinity,
    Sched_getaffinity,
    Set_thread_area,
    Io_setup,
    Io_destroy,
    Io_getevents,
    Io_submit,
    Io_cancel,
    Get_thread_area,
    Lookup_dcookie,
    Epoll_create,
    Epoll_ctl_old,
    Epoll_wait_old,
    Remap_file_pages,
    Getdents64,
    Set_tid_address,
    Restart_syscall,
    Semtimedop,
    Fadvise64,
    Timer_create,
    Timer_settime,
    Timer_gettime,
    Timer_getoverrun,
    Timer_delete,
    Clock_settime,
    Clock_gettime,
    Clock_getres,
    Clock_nanosleep,
    Exit_group,
    Epoll_wait,
    Epoll_ctl,
    Tgkill,
    Utimes,
    Vserver,
    Mbind,
    Set_mempolicy,
    Get_mempolicy,
    Mq_open,
    Mq_unlink,
    Mq_timedsend,
    Mq_timedreceive,
    Mq_notify,
    Mq_getsetattr,
    Kexec_load,
    Waitid,
    Add_key,
    Request_key,
    Keyctl,
    Ioprio_set,
    Ioprio_get,
    Inotify_init,
    Inotify_add_watch,
    Inotify_rm_watch,
    Migrate_pages,
    Openat,
    Mkdirat,
    Mknodat,
    Fchownat,
    Futimesat,
    Newfstatat,
    Unlinkat,
    Renameat,
    Linkat,
    Symlinkat,
    Readlinkat,
    Fchmodat,
    Faccessat,
    Pselect6,
    Ppoll,
    Unshare,
    Set_robust_list,
    Get_robust_list,
    Splice,
    Tee,
    Sync_file_range,
    Vmsplice,
    Move_pages,
    Utimensat,
    Epoll_pwait,
    Signalfd,
    Timerfd_create,
    Eventfd,
    Fallocate,
    Timerfd_settime,
    Timerfd_gettime,
    Accept4,
    Signalfd4,
    Eventfd2,
    Epoll_create1,
    Dup3,
    Pipe2,
    Inotify_init1,
    Preadv,
    Pwritev,
    Rt_tgsigqueueinfo,
    Perf_event_open,
    Recvmmsg,
    Fanotify_init,
    Fanotify_mark,
    Prlimit64,
    Name_to_handle_at,
    Open_by_handle_at,
    Clock_adjtime,
    Syncfs,
    Sendmmsg,
    Setns,
    Getcpu,
    Process_vm_readv,
    Process_vm_writev,
    Kcmp,
    Finit_module,
    Sched_setattr,
    Sched_getattr,
    Renameat2,
    Seccomp,
    Getrandom,
    Memfd_create,
    Kexec_file_load,
    Bpf,
    Execveat,
    Userfaultfd,
    Membarrier,
    Mlock2,
    Copy_file_range,
    Preadv2,
    Pwritev2,
    Pkey_mprotect,
    Pkey_alloc,
    Pkey_free,
    Unknown(c_ulonglong),
}

impl From<user_regs_struct> for Syscall {
    fn from(registers: user_regs_struct) -> Self {
        use Syscall::*;
        match registers.orig_rax as i64 {
            libc::SYS_read => Read,
            libc::SYS_write => Write,
            libc::SYS_open => Open,
            libc::SYS_close => Close,
            libc::SYS_stat => Stat,
            libc::SYS_fstat => Fstat,
            libc::SYS_lstat => Lstat,
            libc::SYS_poll => Poll,
            libc::SYS_lseek => Lseek,
            libc::SYS_mmap => Mmap,
            libc::SYS_mprotect => Mprotect,
            libc::SYS_munmap => Munmap,
            libc::SYS_brk => Brk,
            libc::SYS_rt_sigaction => Rt_sigaction,
            libc::SYS_rt_sigprocmask => Rt_sigprocmask,
            libc::SYS_rt_sigreturn => Rt_sigreturn,
            libc::SYS_ioctl => Ioctl,
            libc::SYS_pread64 => Pread64,
            libc::SYS_pwrite64 => Pwrite64,
            libc::SYS_readv => Readv,
            libc::SYS_writev => Writev,
            libc::SYS_access => Access,
            libc::SYS_pipe => Pipe,
            libc::SYS_select => Select,
            libc::SYS_sched_yield => Sched_yield,
            libc::SYS_mremap => Mremap,
            libc::SYS_msync => Msync,
            libc::SYS_mincore => Mincore,
            libc::SYS_madvise => Madvise,
            libc::SYS_shmget => Shmget,
            libc::SYS_shmat => Shmat,
            libc::SYS_shmctl => Shmctl,
            libc::SYS_dup => Dup,
            libc::SYS_dup2 => Dup2,
            libc::SYS_pause => Pause,
            libc::SYS_nanosleep => Nanosleep,
            libc::SYS_getitimer => Getitimer,
            libc::SYS_alarm => Alarm,
            libc::SYS_setitimer => Setitimer,
            libc::SYS_getpid => Getpid,
            libc::SYS_sendfile => Sendfile,
            libc::SYS_socket => Socket,
            libc::SYS_connect => Connect,
            libc::SYS_accept => Accept,
            libc::SYS_sendto => Sendto,
            libc::SYS_recvfrom => Recvfrom,
            libc::SYS_sendmsg => Sendmsg,
            libc::SYS_recvmsg => Recvmsg,
            libc::SYS_shutdown => Shutdown,
            libc::SYS_bind => Bind,
            libc::SYS_listen => Listen,
            libc::SYS_getsockname => Getsockname,
            libc::SYS_getpeername => Getpeername,
            libc::SYS_socketpair => Socketpair,
            libc::SYS_setsockopt => Setsockopt,
            libc::SYS_getsockopt => Getsockopt,
            libc::SYS_clone => Clone,
            libc::SYS_fork => Fork,
            libc::SYS_vfork => Vfork,
            libc::SYS_execve => Execve,
            libc::SYS_exit => Exit,
            libc::SYS_wait4 => Wait4,
            libc::SYS_kill => Kill,
            libc::SYS_uname => Uname,
            libc::SYS_semget => Semget,
            libc::SYS_semop => Semop,
            libc::SYS_semctl => Semctl,
            libc::SYS_shmdt => Shmdt,
            libc::SYS_msgget => Msgget,
            libc::SYS_msgsnd => Msgsnd,
            libc::SYS_msgrcv => Msgrcv,
            libc::SYS_msgctl => Msgctl,
            libc::SYS_fcntl => Fcntl,
            libc::SYS_flock => Flock,
            libc::SYS_fsync => Fsync,
            libc::SYS_fdatasync => Fdatasync,
            libc::SYS_truncate => Truncate,
            libc::SYS_ftruncate => Ftruncate,
            libc::SYS_getdents => Getdents,
            libc::SYS_getcwd => Getcwd,
            libc::SYS_chdir => Chdir,
            libc::SYS_fchdir => Fchdir,
            libc::SYS_rename => Rename,
            libc::SYS_mkdir => Mkdir,
            libc::SYS_rmdir => Rmdir,
            libc::SYS_creat => Creat,
            libc::SYS_link => Link,
            libc::SYS_unlink => Unlink,
            libc::SYS_symlink => Symlink,
            libc::SYS_readlink => Readlink,
            libc::SYS_chmod => Chmod,
            libc::SYS_fchmod => Fchmod,
            libc::SYS_chown => Chown,
            libc::SYS_fchown => Fchown,
            libc::SYS_lchown => Lchown,
            libc::SYS_umask => Umask,
            libc::SYS_gettimeofday => Gettimeofday,
            libc::SYS_getrlimit => Getrlimit,
            libc::SYS_getrusage => Getrusage,
            libc::SYS_sysinfo => Sysinfo,
            libc::SYS_times => Times,
            libc::SYS_ptrace => Ptrace,
            libc::SYS_getuid => Getuid,
            libc::SYS_syslog => Syslog,
            libc::SYS_getgid => Getgid,
            libc::SYS_setuid => Setuid,
            libc::SYS_setgid => Setgid,
            libc::SYS_geteuid => Geteuid,
            libc::SYS_getegid => Getegid,
            libc::SYS_setpgid => Setpgid,
            libc::SYS_getppid => Getppid,
            libc::SYS_getpgrp => Getpgrp,
            libc::SYS_setsid => Setsid,
            libc::SYS_setreuid => Setreuid,
            libc::SYS_setregid => Setregid,
            libc::SYS_getgroups => Getgroups,
            libc::SYS_setgroups => Setgroups,
            libc::SYS_setresuid => Setresuid,
            libc::SYS_getresuid => Getresuid,
            libc::SYS_setresgid => Setresgid,
            libc::SYS_getresgid => Getresgid,
            libc::SYS_getpgid => Getpgid,
            libc::SYS_setfsuid => Setfsuid,
            libc::SYS_setfsgid => Setfsgid,
            libc::SYS_getsid => Getsid,
            libc::SYS_capget => Capget,
            libc::SYS_capset => Capset,
            libc::SYS_rt_sigpending => Rt_sigpending,
            libc::SYS_rt_sigtimedwait => Rt_sigtimedwait,
            libc::SYS_rt_sigqueueinfo => Rt_sigqueueinfo,
            libc::SYS_rt_sigsuspend => Rt_sigsuspend,
            libc::SYS_sigaltstack => Sigaltstack,
            libc::SYS_utime => Utime,
            libc::SYS_mknod => Mknod,
            libc::SYS_uselib => Uselib,
            libc::SYS_personality => Personality,
            libc::SYS_ustat => Ustat,
            libc::SYS_statfs => Statfs,
            libc::SYS_fstatfs => Fstatfs,
            libc::SYS_sysfs => Sysfs,
            libc::SYS_getpriority => Getpriority,
            libc::SYS_setpriority => Setpriority,
            libc::SYS_sched_setparam => Sched_setparam,
            libc::SYS_sched_getparam => Sched_getparam,
            libc::SYS_sched_setscheduler => Sched_setscheduler,
            libc::SYS_sched_getscheduler => Sched_getscheduler,
            libc::SYS_sched_get_priority_max => Sched_get_priority_max,
            libc::SYS_sched_get_priority_min => Sched_get_priority_min,
            libc::SYS_sched_rr_get_interval => Sched_rr_get_interval,
            libc::SYS_mlock => Mlock,
            libc::SYS_munlock => Munlock,
            libc::SYS_mlockall => Mlockall,
            libc::SYS_munlockall => Munlockall,
            libc::SYS_vhangup => Vhangup,
            libc::SYS_modify_ldt => Modify_ldt,
            libc::SYS_pivot_root => Pivot_root,
            libc::SYS__sysctl => _sysctl,
            libc::SYS_prctl => Prctl,
            libc::SYS_arch_prctl => Arch_prctl,
            libc::SYS_adjtimex => Adjtimex,
            libc::SYS_setrlimit => Setrlimit,
            libc::SYS_chroot => Chroot,
            libc::SYS_sync => Sync,
            libc::SYS_acct => Acct,
            libc::SYS_settimeofday => Settimeofday,
            libc::SYS_mount => Mount,
            libc::SYS_umount2 => Umount2,
            libc::SYS_swapon => Swapon,
            libc::SYS_swapoff => Swapoff,
            libc::SYS_reboot => Reboot,
            libc::SYS_sethostname => Sethostname,
            libc::SYS_setdomainname => Setdomainname,
            libc::SYS_iopl => Iopl,
            libc::SYS_ioperm => Ioperm,
            libc::SYS_create_module => Create_module,
            libc::SYS_init_module => Init_module,
            libc::SYS_delete_module => Delete_module,
            libc::SYS_get_kernel_syms => Get_kernel_syms,
            libc::SYS_query_module => Query_module,
            libc::SYS_quotactl => Quotactl,
            libc::SYS_nfsservctl => Nfsservctl,
            libc::SYS_getpmsg => Getpmsg,
            libc::SYS_putpmsg => Putpmsg,
            libc::SYS_afs_syscall => Afs_syscall,
            libc::SYS_tuxcall => Tuxcall,
            libc::SYS_security => Security,
            libc::SYS_gettid => Gettid,
            libc::SYS_readahead => Readahead,
            libc::SYS_setxattr => Setxattr,
            libc::SYS_lsetxattr => Lsetxattr,
            libc::SYS_fsetxattr => Fsetxattr,
            libc::SYS_getxattr => Getxattr,
            libc::SYS_lgetxattr => Lgetxattr,
            libc::SYS_fgetxattr => Fgetxattr,
            libc::SYS_listxattr => Listxattr,
            libc::SYS_llistxattr => Llistxattr,
            libc::SYS_flistxattr => Flistxattr,
            libc::SYS_removexattr => Removexattr,
            libc::SYS_lremovexattr => Lremovexattr,
            libc::SYS_fremovexattr => Fremovexattr,
            libc::SYS_tkill => Tkill,
            libc::SYS_time => Time,
            libc::SYS_futex => Futex,
            libc::SYS_sched_setaffinity => Sched_setaffinity,
            libc::SYS_sched_getaffinity => Sched_getaffinity,
            libc::SYS_set_thread_area => Set_thread_area,
            libc::SYS_io_setup => Io_setup,
            libc::SYS_io_destroy => Io_destroy,
            libc::SYS_io_getevents => Io_getevents,
            libc::SYS_io_submit => Io_submit,
            libc::SYS_io_cancel => Io_cancel,
            libc::SYS_get_thread_area => Get_thread_area,
            libc::SYS_lookup_dcookie => Lookup_dcookie,
            libc::SYS_epoll_create => Epoll_create,
            libc::SYS_epoll_ctl_old => Epoll_ctl_old,
            libc::SYS_epoll_wait_old => Epoll_wait_old,
            libc::SYS_remap_file_pages => Remap_file_pages,
            libc::SYS_getdents64 => Getdents64,
            libc::SYS_set_tid_address => Set_tid_address,
            libc::SYS_restart_syscall => Restart_syscall,
            libc::SYS_semtimedop => Semtimedop,
            libc::SYS_fadvise64 => Fadvise64,
            libc::SYS_timer_create => Timer_create,
            libc::SYS_timer_settime => Timer_settime,
            libc::SYS_timer_gettime => Timer_gettime,
            libc::SYS_timer_getoverrun => Timer_getoverrun,
            libc::SYS_timer_delete => Timer_delete,
            libc::SYS_clock_settime => Clock_settime,
            libc::SYS_clock_gettime => Clock_gettime,
            libc::SYS_clock_getres => Clock_getres,
            libc::SYS_clock_nanosleep => Clock_nanosleep,
            libc::SYS_exit_group => Exit_group,
            libc::SYS_epoll_wait => Epoll_wait,
            libc::SYS_epoll_ctl => Epoll_ctl,
            libc::SYS_tgkill => Tgkill,
            libc::SYS_utimes => Utimes,
            libc::SYS_vserver => Vserver,
            libc::SYS_mbind => Mbind,
            libc::SYS_set_mempolicy => Set_mempolicy,
            libc::SYS_get_mempolicy => Get_mempolicy,
            libc::SYS_mq_open => Mq_open,
            libc::SYS_mq_unlink => Mq_unlink,
            libc::SYS_mq_timedsend => Mq_timedsend,
            libc::SYS_mq_timedreceive => Mq_timedreceive,
            libc::SYS_mq_notify => Mq_notify,
            libc::SYS_mq_getsetattr => Mq_getsetattr,
            libc::SYS_kexec_load => Kexec_load,
            libc::SYS_waitid => Waitid,
            libc::SYS_add_key => Add_key,
            libc::SYS_request_key => Request_key,
            libc::SYS_keyctl => Keyctl,
            libc::SYS_ioprio_set => Ioprio_set,
            libc::SYS_ioprio_get => Ioprio_get,
            libc::SYS_inotify_init => Inotify_init,
            libc::SYS_inotify_add_watch => Inotify_add_watch,
            libc::SYS_inotify_rm_watch => Inotify_rm_watch,
            libc::SYS_migrate_pages => Migrate_pages,
            libc::SYS_openat => Openat,
            libc::SYS_mkdirat => Mkdirat,
            libc::SYS_mknodat => Mknodat,
            libc::SYS_fchownat => Fchownat,
            libc::SYS_futimesat => Futimesat,
            libc::SYS_newfstatat => Newfstatat,
            libc::SYS_unlinkat => Unlinkat,
            libc::SYS_renameat => Renameat,
            libc::SYS_linkat => Linkat,
            libc::SYS_symlinkat => Symlinkat,
            libc::SYS_readlinkat => Readlinkat,
            libc::SYS_fchmodat => Fchmodat,
            libc::SYS_faccessat => Faccessat,
            libc::SYS_pselect6 => Pselect6,
            libc::SYS_ppoll => Ppoll,
            libc::SYS_unshare => Unshare,
            libc::SYS_set_robust_list => Set_robust_list,
            libc::SYS_get_robust_list => Get_robust_list,
            libc::SYS_splice => Splice,
            libc::SYS_tee => Tee,
            libc::SYS_sync_file_range => Sync_file_range,
            libc::SYS_vmsplice => Vmsplice,
            libc::SYS_move_pages => Move_pages,
            libc::SYS_utimensat => Utimensat,
            libc::SYS_epoll_pwait => Epoll_pwait,
            libc::SYS_signalfd => Signalfd,
            libc::SYS_timerfd_create => Timerfd_create,
            libc::SYS_eventfd => Eventfd,
            libc::SYS_fallocate => Fallocate,
            libc::SYS_timerfd_settime => Timerfd_settime,
            libc::SYS_timerfd_gettime => Timerfd_gettime,
            libc::SYS_accept4 => Accept4,
            libc::SYS_signalfd4 => Signalfd4,
            libc::SYS_eventfd2 => Eventfd2,
            libc::SYS_epoll_create1 => Epoll_create1,
            libc::SYS_dup3 => Dup3,
            libc::SYS_pipe2 => Pipe2,
            libc::SYS_inotify_init1 => Inotify_init1,
            libc::SYS_preadv => Preadv,
            libc::SYS_pwritev => Pwritev,
            libc::SYS_rt_tgsigqueueinfo => Rt_tgsigqueueinfo,
            libc::SYS_perf_event_open => Perf_event_open,
            libc::SYS_recvmmsg => Recvmmsg,
            libc::SYS_fanotify_init => Fanotify_init,
            libc::SYS_fanotify_mark => Fanotify_mark,
            libc::SYS_prlimit64 => Prlimit64,
            libc::SYS_name_to_handle_at => Name_to_handle_at,
            libc::SYS_open_by_handle_at => Open_by_handle_at,
            libc::SYS_clock_adjtime => Clock_adjtime,
            libc::SYS_syncfs => Syncfs,
            libc::SYS_sendmmsg => Sendmmsg,
            libc::SYS_setns => Setns,
            libc::SYS_getcpu => Getcpu,
            libc::SYS_process_vm_readv => Process_vm_readv,
            libc::SYS_process_vm_writev => Process_vm_writev,
            libc::SYS_kcmp => Kcmp,
            libc::SYS_finit_module => Finit_module,
            libc::SYS_sched_setattr => Sched_setattr,
            libc::SYS_sched_getattr => Sched_getattr,
            libc::SYS_renameat2 => Renameat2,
            libc::SYS_seccomp => Seccomp,
            libc::SYS_getrandom => Getrandom,
            libc::SYS_memfd_create => Memfd_create,
            libc::SYS_kexec_file_load => Kexec_file_load,
            libc::SYS_bpf => Bpf,
            libc::SYS_execveat => Execveat,
            libc::SYS_userfaultfd => Userfaultfd,
            libc::SYS_membarrier => Membarrier,
            libc::SYS_mlock2 => Mlock2,
            libc::SYS_copy_file_range => Copy_file_range,
            libc::SYS_preadv2 => Preadv2,
            libc::SYS_pwritev2 => Pwritev2,
            libc::SYS_pkey_mprotect => Pkey_mprotect,
            libc::SYS_pkey_alloc => Pkey_alloc,
            libc::SYS_pkey_free => Pkey_free,
            _ => Unknown(registers.orig_rax),
        }
    }
}
